### ISSUE TITLE
impimonitor Problem feedback

### ISSUE THREAD

**Issue by freeflyday** [soundcloud/ipmi_exporter#23]
![image](https://user-images.githubusercontent.com/18246614/55447849-0b384c00-55f8-11e9-8017-ad08983b32ff.png)

**Comment by bitfehler** [comment]
Hi,
thanks for your feedback. However, if I understand your screenshot correctly, this is not an issue with the exporter. It seems to me your problem is that you can use `ipmitool` on `192.168.43.71` but not `ipmimonitoring`?

If so, I am afraid I won't be able to help you much. There are a ton of reasons why this could be the case, and if it is an actual bug it would be withing FreeIPMI. Though I would guess that playing with the configuration might help here. One thing that comes to mind is maybe try adding `-l ADMIN` to `ipmimonitoring`. FreeIPMI defaults to OPERATOR there, whereas ipmitool defaults to ADMINISTRATOR. Otherwise, maybe adding `--debug` will give you a better hint. 

Other than that, there is not much I can do for you. Feel free to post any further questions here or re-open if I misunderstood your report, but I am going to close this issue, as it is not related to the exporter. If you wish, you can also contact the [FreeIPMI folks](https://www.gnu.org/software/freeipmi/) about this.

**Comment by freeflyday** [comment]
Hello,
    I do want to show that using ipmimonitor is problematic when using ipmitool normally. This question is to show whether ipmi_exporter can be further optimized and more general-purpose, because when I use ipmi_exporter, it is very convenient in most cases, but there are some exceptions, such as the problems I mentioned above, I can not be solved, whether further optimization can be more general and can solve the problems I encounter, so ipmi_exporter is perfect. 。 Finally, I tried the plus-l admin parameter you mentioned, but it failed.
