### ISSUE TITLE
Testing a target

### ISSUE THREAD

**Issue by jdbarnes-isi** [soundcloud/ipmi_exporter#53]
Hello,
I am relatively new to prometheus and exporters, and I have configured this exporter to get status info from our out-of-band bmc/ipmi targets. The problem I am having is that no matter what password I enter into the "default" module, I get an error stating
```password invalid\n" source="collector.go:249"```
If I want to send a curl request to the node exporter to query a remote target, how would I go about doing this?
For example, would this work, or do I have to construct a json string in order to test a target before entering it into my prometheus configuration?
```
curl http://localhost:9290/ipmi?target=192.168.100.1&user=admin&password=password&driver=lanplus
```
Thank you.

**Comment by bitfehler** [comment]
Hi,
you can curl the exporter, but you cannot pass settings this way. You will have to construct a module, default or otherwise, that has the desired settings (user, password, driver, etc), and then you can `curl http://localhost:9290/ipmi?target=192.168.100.1&module=default`.

If things still don't work for you, I am wondering if this might be somehow related to #16 - do your passwords contain any special characters, like backticks or such? Could you maybe as a test try to set the passwords to something purely alphanumeric temporarily and see if that makes any difference?

**Comment by jdbarnes-isi** [comment]
It turns out that it's my fault and the password in the module was not the correct one. Thanks for clarifying that it's not possible to test/troubleshoot via command line alone.
